server.port=8085

spring.application.name=gully-cricket-backend

spring.data.mongodb.uri=mongodb+srv://23ata05174_db_user:GpiBQ3ANnWS9UYln@cluster0.x2p9yrs.mongodb.net/gulli_cricket
spring.data.mongodb.auto-index-creation=true

jwt.secret=GulliCricketSuperSecretKeyForAuthenticationSigningKey2026!
jwt.expiration=86400000

logging.level.com.gullyCricket=DEBUG
logging.level.org.springframework.data.mongodb=INFO